[package]
name = "yback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16.0"
env_logger = "0.9.0"
json = "0.12.4"
log = "0.4.14"
regex = "1.5.4"

